# Sử dụng Nginx làm base image
FROM nginx:latest

# Sao chép file index.html từ thư mục hiện tại vào container
COPY ./index.html /usr/share/nginx/html/

# Mở cổng 80 để truy cập vào trang web
EXPOSE 80
